/**
 * Fallback Generator Service
 * 
 * Provides intelligent fallback generation when Gemini API is unavailable.
 * Uses simple heuristics and defaults to create functional waitlist pages.
 * Requirements: 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.8
 */

import { generateSlug } from '../utils/slug-generator';
import type { GenerationRequest } from '../utils/input-validator';

/**
 * Template IDs available in the system
 */
export type TemplateId = 'minimal' | 'bold' | 'startup' | 'product' | 'comingSoon';

/**
 * Font pair IDs available in the system
 */
export type FontPairId = 'inter' | 'outfit' | 'space' | 'playfair' | 'montserrat' | 'poppins' | 'raleway' | 'dm-sans';

/**
 * Design package generated by fallback
 */
export interface DesignPackage {
  template: TemplateId;
  primaryColor: string;
  fontFamily: FontPairId;
  backgroundType: 'solid' | 'gradient' | 'image';
  backgroundValue: string;
  showCounter: boolean;
}

/**
 * Copy content generated by fallback
 */
export interface CopyContent {
  headline: string;
  tagline: string;
  description: string;
  ctaText: string;
  features?: Feature[];
}

/**
 * Feature item
 */
export interface Feature {
  icon: string;
  title: string;
  description: string;
}

/**
 * Complete generation response
 */
export interface GenerationResponse {
  design: DesignPackage;
  copy: CopyContent;
  slug: string;
}

/**
 * Fallback Generator Service
 * 
 * Generates basic but functional waitlist configurations when AI is unavailable
 */
export class FallbackGeneratorService {
  /**
   * Generates a complete waitlist configuration using fallback logic
   * 
   * @param request - The generation request
   * @returns Complete generation response
   */
  generate(request: GenerationRequest): GenerationResponse {
    return {
      design: this.generateDesign(request),
      copy: this.generateCopy(request),
      slug: this.generateSlug(request.productName),
    };
  }

  /**
   * Generates a design package using default values
   * 
   * Strategy:
   * - Always use minimal template (safest, most versatile)
   * - Use neutral gray color scheme
   * - Use Inter font (professional, readable)
   * - Use solid light background
   * - Show counter by default
   * 
   * @param request - The generation request
   * @returns Design package
   */
  generateDesign(request: GenerationRequest): DesignPackage {
    return {
      template: this.selectDefaultTemplate(),
      primaryColor: this.generateDefaultColor(),
      fontFamily: this.selectDefaultFont(),
      backgroundType: 'solid',
      backgroundValue: '#FAFAFA',
      showCounter: true,
    };
  }

  /**
   * Generates copy content using user-provided description
   * 
   * Strategy:
   * - Use product name as headline
   * - Create simple tagline from description
   * - Use full description as-is
   * - Use generic but effective CTA
   * - No features (requires AI to generate meaningful ones)
   * 
   * @param request - The generation request
   * @returns Copy content
   */
  generateCopy(request: GenerationRequest): CopyContent {
    const { productName, shortDescription } = request;

    // Create a simple headline from product name
    const headline = this.createHeadline(productName);

    // Create a tagline from the first sentence of description
    const tagline = this.createTagline(shortDescription);

    // Use the full description
    const description = shortDescription;

    // Generate a simple CTA
    const ctaText = this.generateCTA(productName);

    return {
      headline,
      tagline,
      description,
      ctaText,
      // No features in fallback mode - requires AI to generate meaningful ones
      features: undefined,
    };
  }

  /**
   * Generates a URL slug from product name
   * 
   * @param productName - The product name
   * @returns URL slug
   */
  generateSlug(productName: string): string {
    return generateSlug(productName);
  }

  /**
   * Selects the default template
   * 
   * @returns Default template ID (minimal)
   */
  private selectDefaultTemplate(): TemplateId {
    return 'minimal';
  }

  /**
   * Generates the default primary color
   * 
   * @returns Default color (neutral dark gray)
   */
  private generateDefaultColor(): string {
    return '#18181b'; // Zinc-900 - professional, neutral
  }

  /**
   * Selects the default font family
   * 
   * @returns Default font ID (inter)
   */
  private selectDefaultFont(): FontPairId {
    return 'inter'; // Most professional and readable
  }

  /**
   * Creates a headline from product name
   * 
   * Ensures headline is between 30-80 characters
   * 
   * @param productName - The product name
   * @returns Headline
   */
  private createHeadline(productName: string): string {
    // If product name is too short, add context
    if (productName.length < 30) {
      return `Join the ${productName} Waitlist`;
    }

    // If product name is good length, use as-is
    if (productName.length <= 80) {
      return productName;
    }

    // If too long, truncate
    return productName.substring(0, 77) + '...';
  }

  /**
   * Creates a tagline from description
   * 
   * Extracts first sentence or first 100 characters
   * 
   * @param description - The product description
   * @returns Tagline
   */
  private createTagline(description: string): string {
    // Try to get first sentence
    const firstSentence = description.split(/[.!?]/)[0].trim();

    if (firstSentence.length > 0 && firstSentence.length <= 100) {
      return firstSentence;
    }

    // Otherwise, take first 100 characters
    if (description.length <= 100) {
      return description;
    }

    return description.substring(0, 97) + '...';
  }

  /**
   * Generates a CTA button text
   * 
   * Creates a simple, action-oriented CTA
   * 
   * @param productName - The product name
   * @returns CTA text
   */
  private generateCTA(productName: string): string {
    // Simple, effective CTAs
    const ctas = [
      'Join the waitlist',
      'Get early access',
      'Sign up now',
      'Reserve your spot',
      'Join now',
    ];

    // Use first CTA as default (most common)
    return ctas[0];
  }
}

// Export singleton instance
export const fallbackGeneratorService = new FallbackGeneratorService();
